"""Client-facing deliverables: an analysis brief and a presentation deck.

The brief is the document a consultant hands over. It states what was received, what
was repaired and why, what the numbers say, what is forecast, and — kept deliberately
separate — what the analysis does not establish. Nothing in it is generated by a
language model, so every sentence traces back to an arithmetic result.
"""

from __future__ import annotations

import io
from datetime import UTC, datetime
from typing import Any

from pptx import Presentation
from pptx.chart.data import CategoryChartData
from pptx.dml.color import RGBColor
from pptx.enum.chart import XL_CHART_TYPE, XL_LEGEND_POSITION
from pptx.enum.text import PP_ALIGN
from pptx.presentation import Presentation as PptxPresentation
from pptx.util import Emu, Inches, Pt

from . import arabic as ar
from .errors import AppError

# Slide geometry, 16:9.
SLIDE_WIDTH = Inches(13.333)
SLIDE_HEIGHT = Inches(7.5)

INK = RGBColor(0x14, 0x25, 0x36)
MUTED = RGBColor(0x52, 0x69, 0x7E)
TEAL = RGBColor(0x08, 0x7F, 0x8C)
AMBER = RGBColor(0x99, 0x62, 0x0A)
RED = RGBColor(0xA4, 0x36, 0x3D)
GREEN = RGBColor(0x19, 0x70, 0x4A)
PAPER = RGBColor(0xFF, 0xFF, 0xFF)
CANVAS = RGBColor(0xF4, 0xF5, 0xF2)
LINE = RGBColor(0xDF, 0xE4, 0xE3)

SEVERITY_COLOR = {
    "critical": RED,
    "high": RED,
    "medium": AMBER,
    "low": TEAL,
    "info": MUTED,
}
SEVERITY_LABEL = {
    "critical": {"en": "Critical", "ar": "حرج"},
    "high": {"en": "High", "ar": "مرتفع"},
    "medium": {"en": "Medium", "ar": "متوسط"},
    "low": {"en": "Low", "ar": "منخفض"},
    "info": {"en": "Context", "ar": "سياق"},
}

TEXT = {
    "brief_title": {"en": "Data analysis brief", "ar": "موجز تحليل البيانات"},
    "prepared": {"en": "Prepared", "ar": "أُعدّ في"},
    "dataset": {"en": "Dataset", "ar": "مجموعة البيانات"},
    "summary": {"en": "Executive summary", "ar": "الملخص التنفيذي"},
    "quality": {"en": "Data received and its condition", "ar": "البيانات المستلمة وحالتها"},
    "cleaning": {"en": "What was repaired, and why", "ar": "ما جرى إصلاحه ولماذا"},
    "findings": {"en": "Findings", "ar": "النتائج"},
    "forecast": {"en": "Outlook", "ar": "النظرة المستقبلية"},
    "actions": {"en": "Recommended actions", "ar": "الإجراءات الموصى بها"},
    "limits": {"en": "What this analysis does not establish", "ar": "ما لا يثبته هذا التحليل"},
    "method": {"en": "Method and reproducibility", "ar": "المنهج وقابلية إعادة الإنتاج"},
    "observation": {"en": "Observed", "ar": "الملاحظة"},
    "interpretation": {"en": "Reading", "ar": "التفسير"},
    "recommendation": {"en": "Action", "ar": "الإجراء"},
    "limitation": {"en": "Limit", "ar": "الحد"},
    "no_findings": {
        "en": "No finding met the reporting threshold on this dataset.",
        "ar": "لم تتجاوز أي نتيجة عتبة الإبلاغ في هذه البيانات.",
    },
    "rows": {"en": "Rows", "ar": "الصفوف"},
    "columns": {"en": "Columns", "ar": "الأعمدة"},
    "score": {"en": "Quality score", "ar": "مؤشر الجودة"},
    "severity": {"en": "Severity", "ar": "الخطورة"},
    "assessment": {"en": "Assessment", "ar": "التقييم"},
    "history": {"en": "History", "ar": "التاريخ"},
    "projected": {"en": "Projected", "ar": "متوقّع"},
    "confidence_band": {"en": "Interval", "ar": "الفاصل"},
    "accuracy": {"en": "Measured accuracy", "ar": "الدقة المقاسة"},
    "decision": {"en": "Decision required", "ar": "قرار مطلوب"},
}

GRADE_LABEL = {
    "ready": {"en": "Ready for reporting", "ar": "جاهزة للتقارير"},
    "usable_with_caveats": {"en": "Usable with caveats", "ar": "قابلة للاستخدام مع تحفظات"},
    "repair_required": {"en": "Repair required", "ar": "تحتاج إصلاحًا"},
    "not_fit_for_reporting": {"en": "Not fit for reporting", "ar": "غير صالحة للتقارير"},
    "not_assessable": {"en": "Not assessable", "ar": "غير قابلة للتقييم"},
}


def _t(key: str, locale: str) -> str:
    return TEXT[key]["ar" if locale == "ar" else "en"]


def _localized(value: Any, locale: str, fallback: str = "") -> str:
    if isinstance(value, dict):
        return str(value.get("ar" if locale == "ar" else "en", fallback))
    return str(value) if value is not None else fallback


def build_brief(
    *,
    dataset: dict[str, Any],
    profile: dict[str, Any],
    insights: dict[str, Any],
    cleaning: dict[str, Any] | None = None,
    forecast: dict[str, Any] | None = None,
    locale: str = "en",
    organization: str | None = None,
) -> dict[str, Any]:
    """Assemble the structured brief that every export format renders."""
    ready = locale == "ar"
    quality = profile.get("quality") or {}
    findings = insights.get("findings", [])
    counts = insights.get("counts", {})
    urgent = [f for f in findings if f["severity"] in {"critical", "high"}]

    grade = GRADE_LABEL.get(str(quality.get("grade")), {"en": "—", "ar": "—"})
    if ready:
        headline = (
            f"جرى فحص {ar.count(int(profile.get('row_count', 0)), ar.ROW)} في "
            f"{ar.count(int(profile.get('column_count', 0)), ar.COLUMN)}. "
            f"جودة البيانات {quality.get('score', '—')} من 100 ({grade['ar']}). "
            + (
                f"تستدعي {ar.count(len(urgent), ar.FINDING)} انتباهًا فوريًا."
                if urgent
                else "لا توجد نتيجة تستدعي انتباهًا فوريًا."
            )
        )
    else:
        headline = (
            f"{profile.get('row_count', 0):,} rows across "
            f"{profile.get('column_count', 0):,} columns were examined. "
            f"Data quality scores {quality.get('score', '—')}/100 ({grade['en']}). "
            + (
                f"{len(urgent)} finding requires immediate attention."
                if len(urgent) == 1
                else f"{len(urgent)} findings require immediate attention."
                if urgent
                else "No finding requires immediate attention."
            )
        )

    actions = [
        {
            "severity": f["severity"],
            "source": _localized(f["title"], locale),
            "action": _localized(f["recommendation"], locale),
        }
        for f in findings
        if f["severity"] in {"critical", "high", "medium"}
    ]
    limits = [_localized(f["limitation"], locale) for f in findings]
    if forecast:
        limits.extend(forecast.get("limitations_ar" if ready else "limitations", []))
    if cleaning:
        limits.extend(
            cleaning.get("summary", {}).get("caveats", {}).get("ar" if ready else "en", [])
        )

    return {
        "locale": locale,
        "generated_at": datetime.now(UTC).isoformat(timespec="seconds"),
        "organization": organization,
        "dataset": dataset,
        "headline": headline,
        "quality": quality,
        "quality_grade": grade["ar"] if ready else grade["en"],
        "profile_summary": {
            "row_count": profile.get("row_count"),
            "column_count": profile.get("column_count"),
            "issues": profile.get("quality_issues", {}),
            "columns": [
                {
                    "name": name,
                    "type": column.get("semantic_type"),
                    "missing": column.get("null_count"),
                    "missing_rate": column.get("missing_rate"),
                    "distinct": column.get("distinct_count"),
                }
                for name, column in profile.get("column_profiles", {}).items()
            ],
        },
        "cleaning": cleaning.get("summary") if cleaning else None,
        "findings": [
            {
                "id": f["id"],
                "kind": f["kind"],
                "severity": f["severity"],
                "severity_label": SEVERITY_LABEL[f["severity"]]["ar" if ready else "en"],
                "confidence": f["confidence"],
                "title": _localized(f["title"], locale),
                "observation": _localized(f["observation"], locale),
                "interpretation": _localized(f["interpretation"], locale),
                "recommendation": _localized(f["recommendation"], locale),
                "limitation": _localized(f["limitation"], locale),
                "evidence": f.get("evidence", {}),
                "chart": f.get("chart"),
            }
            for f in findings
        ],
        "counts": counts,
        "forecast": forecast,
        "actions": actions,
        "limitations": list(dict.fromkeys(limits)),
        "method": {
            "en": (
                "Findings are produced by deterministic statistical rules over the rows "
                "supplied. No language model contributed a number. Re-running the same "
                "dataset version reproduces this brief exactly."
            ),
            "ar": (
                "تُنتَج النتائج بقواعد إحصائية حتمية على الصفوف المزوَّدة. لم يساهم أي "
                "نموذج لغوي في أي رقم. إعادة تشغيل إصدار البيانات نفسه تعيد إنتاج هذا "
                "الموجز حرفيًا."
            ),
        },
    }


# ----------------------------------------------------------------------------------
# Presentation
# ----------------------------------------------------------------------------------


def _blank(presentation: PptxPresentation) -> Any:
    return presentation.slides.add_slide(presentation.slide_layouts[6])


def _rect(slide: Any, left: Any, top: Any, width: Any, height: Any, color: RGBColor) -> Any:
    from pptx.enum.shapes import MSO_SHAPE

    shape = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, left, top, width, height)
    shape.fill.solid()
    shape.fill.fore_color.rgb = color
    shape.line.fill.background()
    shape.shadow.inherit = False
    return shape


def _text(
    slide: Any,
    left: Any,
    top: Any,
    width: Any,
    height: Any,
    content: str,
    *,
    size: int = 14,
    bold: bool = False,
    color: RGBColor = INK,
    rtl: bool = False,
    align: Any = None,
    spacing: float = 1.15,
) -> Any:
    box = slide.shapes.add_textbox(left, top, width, height)
    frame = box.text_frame
    frame.word_wrap = True
    paragraph = frame.paragraphs[0]
    paragraph.alignment = align or (PP_ALIGN.RIGHT if rtl else PP_ALIGN.LEFT)
    paragraph.line_spacing = spacing
    run = paragraph.add_run()
    run.text = content
    run.font.size = Pt(size)
    run.font.bold = bold
    run.font.color.rgb = color
    run.font.name = "Arial" if rtl else "Calibri"
    if rtl:
        # python-pptx has no RTL property; the paragraph attribute is set directly.
        paragraph._pPr.set("rtl", "1")
    return box


def _bullets(
    slide: Any,
    left: Any,
    top: Any,
    width: Any,
    height: Any,
    items: list[str],
    *,
    size: int = 13,
    rtl: bool = False,
    color: RGBColor = INK,
    marker: str = "—",
) -> None:
    box = slide.shapes.add_textbox(left, top, width, height)
    frame = box.text_frame
    frame.word_wrap = True
    for index, item in enumerate(items):
        paragraph = frame.paragraphs[0] if index == 0 else frame.add_paragraph()
        paragraph.alignment = PP_ALIGN.RIGHT if rtl else PP_ALIGN.LEFT
        paragraph.line_spacing = 1.2
        paragraph.space_after = Pt(8)
        run = paragraph.add_run()
        run.text = f"{item} {marker}" if rtl else f"{marker} {item}"
        run.font.size = Pt(size)
        run.font.color.rgb = color
        run.font.name = "Arial" if rtl else "Calibri"
        if rtl:
            paragraph._pPr.set("rtl", "1")


def _slide_frame(slide: Any, title: str, eyebrow: str, rtl: bool) -> None:
    """Shared chrome: a title, a rule, and a section label."""
    _rect(slide, 0, 0, SLIDE_WIDTH, SLIDE_HEIGHT, PAPER)
    margin = Inches(0.75)
    width = SLIDE_WIDTH - margin * 2
    _text(
        slide,
        margin,
        Inches(0.45),
        width,
        Inches(0.3),
        eyebrow.upper(),
        size=11,
        bold=True,
        color=TEAL,
        rtl=rtl,
    )
    _text(
        slide,
        margin,
        Inches(0.8),
        width,
        Inches(0.7),
        title,
        size=28,
        bold=True,
        color=INK,
        rtl=rtl,
    )
    _rect(slide, margin, Inches(1.62), width, Emu(9525), LINE)


def _title_slide(presentation: PptxPresentation, brief: dict[str, Any], rtl: bool) -> None:
    slide = _blank(presentation)
    _rect(slide, 0, 0, SLIDE_WIDTH, SLIDE_HEIGHT, INK)
    _rect(slide, 0, SLIDE_HEIGHT - Inches(0.28), SLIDE_WIDTH, Inches(0.28), TEAL)
    margin = Inches(1.0)
    width = SLIDE_WIDTH - margin * 2
    _text(
        slide,
        margin,
        Inches(1.6),
        width,
        Inches(0.4),
        "بصيرة  ·  BASEERA",
        size=13,
        bold=True,
        color=TEAL,
        rtl=rtl,
    )
    _text(
        slide,
        margin,
        Inches(2.15),
        width,
        Inches(1.2),
        _t("brief_title", brief["locale"]),
        size=42,
        bold=True,
        color=PAPER,
        rtl=rtl,
    )
    subtitle = brief["dataset"].get("name") or brief["dataset"].get("filename") or ""
    if brief.get("organization"):
        subtitle = f"{brief['organization']} · {subtitle}" if subtitle else brief["organization"]
    _text(
        slide,
        margin,
        Inches(3.5),
        width,
        Inches(0.6),
        subtitle,
        size=18,
        color=RGBColor(0xB2, 0xC1, 0xC4),
        rtl=rtl,
    )
    _text(
        slide,
        margin,
        Inches(4.3),
        width,
        Inches(1.4),
        brief["headline"],
        size=15,
        color=RGBColor(0xD2, 0xDD, 0xDD),
        rtl=rtl,
    )
    stamp = f"{_t('prepared', brief['locale'])}: {brief['generated_at'][:10]}"
    _text(
        slide,
        margin,
        SLIDE_HEIGHT - Inches(1.0),
        width,
        Inches(0.35),
        stamp,
        size=11,
        color=RGBColor(0x91, 0xA5, 0xA9),
        rtl=rtl,
    )


def _quality_slide(presentation: PptxPresentation, brief: dict[str, Any], rtl: bool) -> None:
    slide = _blank(presentation)
    _slide_frame(slide, _t("quality", brief["locale"]), _t("dataset", brief["locale"]), rtl)
    quality = brief.get("quality") or {}
    dimensions = quality.get("dimensions", {})
    margin = Inches(0.75)

    tiles = [
        (_t("rows", brief["locale"]), f"{brief['profile_summary']['row_count']:,}"),
        (_t("columns", brief["locale"]), f"{brief['profile_summary']['column_count']:,}"),
        (_t("score", brief["locale"]), f"{quality.get('score', '—')}"),
        (_t("assessment", brief["locale"]), brief.get("quality_grade", "—")),
    ]
    tile_width = Inches(2.85)
    for index, (label, value) in enumerate(tiles):
        left = margin + index * (tile_width + Inches(0.2))
        _rect(slide, left, Inches(1.95), tile_width, Inches(1.25), CANVAS)
        _text(
            slide,
            left + Inches(0.22),
            Inches(2.08),
            tile_width - Inches(0.4),
            Inches(0.3),
            label,
            size=11,
            color=MUTED,
            rtl=rtl,
        )
        _text(
            slide,
            left + Inches(0.22),
            Inches(2.42),
            tile_width - Inches(0.4),
            Inches(0.6),
            value,
            size=26,
            bold=True,
            color=INK,
            rtl=rtl,
        )

    if dimensions:
        chart_data = CategoryChartData()
        labels_ar = {
            "completeness": "الاكتمال",
            "uniqueness": "التفرّد",
            "validity": "الصلاحية",
            "consistency": "الاتساق",
            "plausibility": "المعقولية",
        }
        chart_data.categories = [
            labels_ar.get(k, k) if rtl else k.replace("_", " ").title() for k in dimensions
        ]
        chart_data.add_series(
            _t("score", brief["locale"]), tuple(round(v * 100, 1) for v in dimensions.values())
        )
        graphic = slide.shapes.add_chart(
            XL_CHART_TYPE.COLUMN_CLUSTERED,
            margin,
            Inches(3.45),
            SLIDE_WIDTH - margin * 2,
            Inches(3.2),
            chart_data,
        )
        chart = graphic.chart
        chart.has_legend = False
        chart.plots[0].vary_by_categories = False
        series = chart.plots[0].series[0]
        series.format.fill.solid()
        series.format.fill.fore_color.rgb = TEAL
        chart.value_axis.maximum_scale = 100
        chart.value_axis.minimum_scale = 0
        chart.value_axis.has_major_gridlines = True


def _cleaning_slide(presentation: PptxPresentation, brief: dict[str, Any], rtl: bool) -> None:
    summary = brief.get("cleaning")
    if not summary:
        return
    slide = _blank(presentation)
    _slide_frame(slide, _t("cleaning", brief["locale"]), _t("method", brief["locale"]), rtl)
    margin = Inches(0.75)
    width = SLIDE_WIDTH - margin * 2
    language = "ar" if rtl else "en"
    _text(
        slide,
        margin,
        Inches(1.85),
        width,
        Inches(0.8),
        summary.get("headline", {}).get(language, ""),
        size=15,
        bold=True,
        color=INK,
        rtl=rtl,
    )
    steps = summary.get("steps", {}).get(language, [])
    _bullets(slide, margin, Inches(2.75), width, Inches(2.4), steps[:8], size=12, rtl=rtl)
    caveats = summary.get("caveats", {}).get(language, [])
    if caveats:
        top: int = Inches(5.25)
        _rect(slide, margin, top, width, Inches(1.55), RGBColor(0xFC, 0xEB, 0xC7))
        _bullets(
            slide,
            margin + Inches(0.25),
            top + Inches(0.18),
            width - Inches(0.5),
            Inches(1.2),
            caveats[:3],
            size=11,
            rtl=rtl,
            color=RGBColor(0x99, 0x62, 0x0A),
            marker="!",
        )


def _finding_slide(
    presentation: PptxPresentation, brief: dict[str, Any], finding: dict[str, Any], rtl: bool
) -> None:
    slide = _blank(presentation)
    _slide_frame(slide, finding["title"], _t("findings", brief["locale"]), rtl)
    margin = Inches(0.75)
    width = SLIDE_WIDTH - margin * 2
    colour = SEVERITY_COLOR.get(finding["severity"], MUTED)

    badge_width = Inches(1.5)
    badge_left = (SLIDE_WIDTH - margin - badge_width) if rtl else margin
    _rect(slide, badge_left, Inches(1.85), badge_width, Inches(0.32), colour)
    _text(
        slide,
        badge_left + Inches(0.12),
        Inches(1.88),
        badge_width - Inches(0.24),
        Inches(0.28),
        finding["severity_label"],
        size=10,
        bold=True,
        color=PAPER,
        rtl=rtl,
        align=PP_ALIGN.CENTER,
    )

    blocks = [
        (_t("observation", brief["locale"]), finding["observation"], INK, 14),
        (_t("interpretation", brief["locale"]), finding["interpretation"], INK, 13),
        (_t("recommendation", brief["locale"]), finding["recommendation"], GREEN, 13),
        (_t("limitation", brief["locale"]), finding["limitation"], MUTED, 11),
    ]
    top: int = Inches(2.4)
    for label, body, tone, size in blocks:
        _text(
            slide, margin, top, width, Inches(0.25), label, size=10, bold=True, color=TEAL, rtl=rtl
        )
        _text(
            slide,
            margin,
            top + Inches(0.26),
            width,
            Inches(0.9),
            body,
            size=size,
            color=tone,
            rtl=rtl,
        )
        top += Inches(1.2)


def _forecast_slide(presentation: PptxPresentation, brief: dict[str, Any], rtl: bool) -> None:
    forecast = brief.get("forecast")
    if not forecast or not forecast.get("forecast"):
        return
    slide = _blank(presentation)
    _slide_frame(slide, _t("forecast", brief["locale"]), _t("projected", brief["locale"]), rtl)
    margin = Inches(0.75)
    width = SLIDE_WIDTH - margin * 2

    history = forecast.get("history", [])[-18:]
    projected = forecast["forecast"]
    categories = [h["period"] for h in history] + [f["period"][:7] for f in projected]
    actual = [h["value"] for h in history] + [None] * len(projected)
    # Join the two lines at the last observed point so the chart has no visible gap.
    joined: list[float | None] = [None] * (len(history) - 1) if history else []
    if history:
        joined.append(history[-1]["value"])
    joined.extend(f["value"] for f in projected)
    lower: list[float | None] = [None] * len(history) + [f["lower"] for f in projected]
    upper: list[float | None] = [None] * len(history) + [f["upper"] for f in projected]

    chart_data = CategoryChartData()
    chart_data.categories = categories
    chart_data.add_series(_t("history", brief["locale"]), tuple(actual))
    chart_data.add_series(_t("projected", brief["locale"]), tuple(joined))
    chart_data.add_series(f"{_t('confidence_band', brief['locale'])} ↓", tuple(lower))
    chart_data.add_series(f"{_t('confidence_band', brief['locale'])} ↑", tuple(upper))
    graphic = slide.shapes.add_chart(
        XL_CHART_TYPE.LINE, margin, Inches(1.9), width, Inches(3.5), chart_data
    )
    chart = graphic.chart
    chart.has_legend = True
    chart.legend.position = XL_LEGEND_POSITION.BOTTOM
    chart.legend.include_in_layout = False
    for index, (colour, dashed) in enumerate(
        [
            (INK, False),
            (TEAL, False),
            (RGBColor(0xB8, 0xD8, 0xDB), True),
            (RGBColor(0xB8, 0xD8, 0xDB), True),
        ]
    ):
        line = chart.plots[0].series[index].format.line
        line.color.rgb = colour
        line.width = Pt(2.5 if not dashed else 1.0)

    backtest = forecast.get("backtest", {})
    if backtest.get("mase") is not None:
        accuracy = (
            f"{_t('accuracy', brief['locale'])}: MASE {backtest['mase']}"
            f" · WAPE {backtest.get('wape')}"
            f" · {_t('confidence_band', brief['locale'])} "
            f"{backtest.get('interval_coverage')}/{backtest.get('interval_target')}"
        )
    else:
        accuracy = _localized(
            {"en": backtest.get("reason", ""), "ar": backtest.get("reason", "")},
            brief["locale"],
        )
    _text(slide, margin, Inches(5.5), width, Inches(0.3), accuracy, size=11, color=MUTED, rtl=rtl)
    warnings = forecast.get("warnings_ar" if rtl else "warnings", [])
    if warnings:
        _bullets(
            slide,
            margin,
            Inches(5.85),
            width,
            Inches(1.1),
            warnings[:2],
            size=11,
            rtl=rtl,
            color=AMBER,
            marker="!",
        )


def _actions_slide(presentation: PptxPresentation, brief: dict[str, Any], rtl: bool) -> None:
    actions = brief.get("actions", [])
    if not actions:
        return
    slide = _blank(presentation)
    _slide_frame(slide, _t("actions", brief["locale"]), _t("findings", brief["locale"]), rtl)
    margin = Inches(0.75)
    width = SLIDE_WIDTH - margin * 2
    top: int = Inches(1.95)
    for index, action in enumerate(actions[:6], start=1):
        colour = SEVERITY_COLOR.get(action["severity"], MUTED)
        row_height = Inches(0.82)
        _rect(slide, margin, top, width, row_height, CANVAS)
        bar_left = (SLIDE_WIDTH - margin - Inches(0.06)) if rtl else margin
        _rect(slide, bar_left, top, Inches(0.06), row_height, colour)
        _text(
            slide,
            margin + Inches(0.3),
            top + Inches(0.08),
            width - Inches(0.6),
            Inches(0.26),
            f"{index}. {action['source']}",
            size=11,
            bold=True,
            color=MUTED,
            rtl=rtl,
        )
        _text(
            slide,
            margin + Inches(0.3),
            top + Inches(0.36),
            width - Inches(0.6),
            Inches(0.42),
            action["action"],
            size=12,
            color=INK,
            rtl=rtl,
        )
        top += row_height + Inches(0.12)


def _limits_slide(presentation: PptxPresentation, brief: dict[str, Any], rtl: bool) -> None:
    slide = _blank(presentation)
    _slide_frame(slide, _t("limits", brief["locale"]), _t("method", brief["locale"]), rtl)
    margin = Inches(0.75)
    width = SLIDE_WIDTH - margin * 2
    _bullets(
        slide,
        margin,
        Inches(1.95),
        width,
        Inches(3.6),
        brief.get("limitations", [])[:7],
        size=12,
        rtl=rtl,
        color=INK,
    )
    _rect(slide, margin, Inches(5.75), width, Inches(1.05), CANVAS)
    _text(
        slide,
        margin + Inches(0.25),
        Inches(5.9),
        width - Inches(0.5),
        Inches(0.8),
        _localized(brief["method"], brief["locale"]),
        size=11,
        color=MUTED,
        rtl=rtl,
    )


def render_presentation(brief: dict[str, Any]) -> bytes:
    """Render the brief as a .pptx deck."""
    rtl = brief["locale"] == "ar"
    presentation = Presentation()
    presentation.slide_width = SLIDE_WIDTH
    presentation.slide_height = SLIDE_HEIGHT

    _title_slide(presentation, brief, rtl)
    _quality_slide(presentation, brief, rtl)
    _cleaning_slide(presentation, brief, rtl)
    ranked = [f for f in brief.get("findings", []) if f["severity"] != "info"][:6]
    for finding in ranked:
        _finding_slide(presentation, brief, finding, rtl)
    _forecast_slide(presentation, brief, rtl)
    _actions_slide(presentation, brief, rtl)
    _limits_slide(presentation, brief, rtl)

    buffer = io.BytesIO()
    presentation.save(buffer)
    return buffer.getvalue()


def brief_export(brief: dict[str, Any], kind: str) -> tuple[bytes, str, str]:
    """Render the brief in one of its supported formats."""
    from .reports import render_brief_document

    kind = kind.lower()
    if kind == "pptx":
        return (
            render_presentation(brief),
            "application/vnd.openxmlformats-officedocument.presentationml.presentation",
            "pptx",
        )
    if kind in {"html", "pdf", "docx", "json", "md"}:
        return render_brief_document(brief, kind)
    raise AppError(
        422,
        "unsupported_export_format",
        "Supported brief formats are: docx, html, json, md, pdf, pptx.",
        details={"requested": kind},
    )
