"""connector_secrets

Revision ID: 0ef99343d0c9
Revises: 7540ee07354b
Create Date: 2026-09-21 12:27:19.836241
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0ef99343d0c9"
down_revision: str | Sequence[str] | None = "7540ee07354b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "connector_secrets",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("organization_id", sa.String(length=64), nullable=False),
        sa.Column("connector_id", sa.String(length=64), nullable=False),
        sa.Column("ciphertext", sa.Text(), nullable=False),
        sa.Column("key_id", sa.String(length=32), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("rotated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["connector_id"],
            ["connectors.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("connector_id"),
    )
    op.create_index(
        op.f("ix_connector_secrets_connector_id"),
        "connector_secrets",
        ["connector_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_connector_secrets_organization_id"),
        "connector_secrets",
        ["organization_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_connector_secrets_organization_id"), table_name="connector_secrets")
    op.drop_index(op.f("ix_connector_secrets_connector_id"), table_name="connector_secrets")
    op.drop_table("connector_secrets")
    # ### end Alembic commands ###
